CREATE DATABASE IF NOT EXISTS accounts;

USE accounts;

CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(345) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT  CURRENT_TIMESTAMP;
);